config/routes.rb
Rails.application.routes.draw do
  get 'shopping/index' => 'shopping#index', as: 'shopping_index'
  get 'shopping/show/:id' => 'shopping#show', as: 'shopping_show'
  get 'shopping/new' => 'shopping#new', as: 'shopping_new'
  post 'shopping/create'=>  'shopping#create', as: 'shopping_create'
  get 'shopping/edit/:id'=> 'shopping#edit', as: 'shopping_edit'
  patch 'shopping/update/:id'=>  'shopping#update', as: 'shopping_update'
  delete 'shopping/destroy/:id'=>  'shopping#destroy', as: 'shopping_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
	validates :name , presence: {message: 'Preençha o nome'}
	validates :addres , presence: {message: 'Informe seu endereço'}
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
   def index
    @shops = Shop.all
  end
 
  def show
    @shop = Shop.find_by(id: params['id'])
  end

  def create
    shop = Shop.new(permit)
    if shop.save
      @msg = 'Salvo com sucessso!'
    else
      @msg = shop.errors.messages
    end
  end

  def edit
      @shop = Shop.find_by(id: params['id'])

  end

  def update
    shop = Shop.find_by(id: params['id'])
    if shop.update_attributes(permit)
      @msg = 'Salvo com sucessso!'
    else
      @msg = shop.errors.messages

    end
  end

  def destroy
    shop = Shop.find_by(id: params['id'])
    if shop.destroy
      @msg = 'Apagado com sucessso!'
    else
      @msg = shop.errors.messages

    end
  end

  private

  def permit
    params['shop'].permit(:name, :addres)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shopping/create.html.erb
<h1><%= @msg %></h1>

app/views/shopping/destroy.html.erb
<%= @msg %>

app/views/shopping/edit.html.erb
<h1>Alterar Shop</h1>
<%= form_for @shop, url: shopping_update_path(@shop.id) do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.label :addres, 'Endereço' %>
	<%= f.text_field :addres %>
	<%= f.submit 'Alterar' %>
<% end %>

app/views/shopping/index.html.erb
<h1>Todos os Shoppings</h1>

<table border = '2px' style='width: 50%'>
	<tr>
		<td>Nome</td>
		<td>Alterar</td>
		<td>Remover</td>
	</tr>
<% @shops.each do |shop|%>
<tr>
	<td><%= link_to shop.name, shopping_show_path(shop.id)  %></td>
	<td><%= link_to 'Alterar', shopping_edit_path(shop.id)  %></td>
	<td><%= link_to 'Remover', shopping_destroy_path(shop.id), :method =>'delete' %></td>
</tr>
<% end %>
</table>

app/views/shopping/new.html.erb
<h1>Cadastro de Shopping</h1>
<%= form_for @shop, url: shopping_create_path do |f| %>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
	<%= f.label :addres, 'Endereço' %>
	<%= f.text_field :addres %>
	<%= f.submit 'Enviar' %>
<% end %>

app/views/shopping/show.html.erb
<h1>Shop data</h1>
<p><strong>Nome:</strong><%= @shop.name %></p>
<p><strong>Endereço:</strong><%= @shop.addres%></p>
<%= link_to 'Voltar', shopping_index_path  %>

app/views/shopping/update.html.erb
<%= @msg %>